pipeline:
  stages:
    - name: stage_15a6
      id: stage_15a6
      steps:
        - name: run1
          run:
            script: exit 0
          id: run1
    - name: run-chained
      id: run_chained
      chain:
        uses: default/edgarproject/gitx_parity_on_dev
        ref: develop-pipe
    - name: run-chained-another-repo
      id: run_chained_another_repo
      chain:
        uses: default/edgarproject/gitx_parity_on_diff_repo_on_dev
        ref: develop
