pipeline:
  stages:
    - name: stage_59a5
      id: stage_59a5
      steps:
        - name: wait
          run:
            script: |-
              echo "sleeeping $SLEEP"
              sleep $SLEEP
            env:
              SLEEP: <+input>
          id: wait
