pipeline:
  name: PIPE-31579-parent1
  identifier: PIPE31579parent1
  projectIdentifier: edgarproject
  orgIdentifier: DoNotDelete_MigratorOrg
  tags: {}
  stages:
    - stage:
        name: wait
        identifier: wait
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 30s
        tags: {}
    - stage:
        name: run-child
        identifier: runchild
        description: ""
        type: Pipeline
        spec:
          org: DoNotDelete_MigratorOrg
          pipeline: PIPE31579child1
          project: edgarproject
          gitBranch: demo1
