pipeline:
  name: child-pipe-1
  identifier: childpipe1
  tags: {}
  projectIdentifier: edgartest
  orgIdentifier: default
  stages:
    - stage:
        name: wait
        identifier: wait
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 31s
        tags: {}
