pipeline:
  name: simple-child-remote
  identifier: simplechildremote
  projectIdentifier: edgartest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: wait
        identifier: wait
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 16s
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hello from remote child"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
